### ISSUE TITLE
Raster plot g_map not showing

### ISSUE THREAD

**Issue by griff10000** [bobverity/Rgeoprofile#7]
Hi I have run the examples in package rgeoprofile which create g_map but it doesn't display.
I am running the code in RStudio on a Windows 10 platform.
Do I need to load a separate library to produce a plot?

**Comment by Michael-Stevens-27** [comment]
Hi!

Could you provide the specific code that you're running and the error that is produced when you run said code in R?

**Comment by griff10000** [comment]
Hi Michael,

 

The R code is straight from the documentation, i.e.

 

---------------------------

library(rgeoprofile)

 

#Using provided dataset for the Boston Strangler Incidents:

data(desalvo)

test <- cgt_profile(desalvo$lat, desalvo$lon)

g_map = sp::SpatialPixelsDataFrame(points = test[c("lons", "lats")], data = test)

g_map <- raster::raster(g_map)

# Assign a Coordinate Reference System for the Raster

raster::crs(g_map) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# Define a Parula Color Pallete for Resultant Jeopardy Surface

library(leaflet) #for mapping the geographic profile

pal <- colorNumeric(pals::parula(200), raster::values(g_map),

                    na.color = "transparent")

leaflet() %>%

  addTiles() %>%

  addProviderTiles('Esri.WorldTopoMap', group = 'Topo') %>%

  addAwesomeMarkers(lng = -71.07357, lat = 42.41322, icon =

                      awesomeIcons(icon = 'home', markerColor = 'green'), popup = 'Residence') %>%

  addRasterImage(g_map, colors = pal, opacity = 0.6) %>%

  addLegend(pal = pal, values = raster::values(g_map), title = 'Score') %>%

  addCircleMarkers(lng = data$lon, lat = data$lat, radius = 4, opacity = 1,

                   fill = 'black', stroke = TRUE, fillOpacity = 0.75, weight = 2,

                   fillColor = "red")

 

-------------------------

 

there is no error as such, it is just that the plot does not show.

 

I am using: R version 3.5.3 (2019-03-11) and RStudio Version 1.2.5042
running under Windows 10 on a standard PC

 

 

Regards,

 

Graham W Griffiths

**Comment by Michael-Stevens-27** [comment]
Hi Graham, 

Your question should be directed to the developers of the other rgeoprofile package, their work revolves around Rossmo's CGT algorithm whereas our package focusses on an updated version of geographic profiling based on a Dirichlet process mixture model. This is news to me! I hadn't realised there is another package with the same name. Thank you for bringing this to our attention, here's a link to the package that you are using.   

https://github.com/JSSpaulding/rgeoprofile/

Best wishes, 
Michael

**Comment by Michael-Stevens-27** [comment]
Hi again Graham, 

In case you're interested, here is a link to the paper associated with the Dirichlet process mixture model for geographic profiling. 

https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12190%4010.1111/%28ISSN%292041-210X.Biogeography

Best,
Michael

**Comment by griff10000** [comment]
Hi Michael,

 

Many thanks for your prompt reply and the link to your paper, which I have downloaded along with the appendix.

 

Strange that there are two packages with the same name.

 

Kind regards,

 

Graham
